#!/usr/bin/env python3
"""Generate the rank-4 semantic-delegation v3 curriculum run config."""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
BASE_CONFIG = (
    ROOT
    / "configs/rlm_rlvr/rerun_depth1_h100_lora_semantic_agg_trainonce/"
    "qwen3_4b_instruct_sanjaya_depth1_llmonly_r004_a008_lr1e-4_s150_8xh100_"
    "train-subcalls-root8-beta1-ff05-judgeguard-semanticaggv2-trainonceeasy-bal35f40v1.toml"
)
OUT_DIR = ROOT / "configs/rlm_rlvr/semantic_delegation_v3_curriculum"
PRIVATE_DATASET_ID = "lsteno/BEEG-agents-semantic-delegation-v3"
OLD_RUN_ID = (
    "rlm-rlvr-qwen3-4b-depth1-llmonly-h100-r4-a8-lr1e-4-s150-"
    "train-subcalls-root8-beta1-ff05-judgeguard-semanticaggv2-trainonceeasy-bal35f40v1"
)
RUN_SUFFIX = "semantic-delegation-v3-curriculum-local80-terminal20-root8-beta1"
RUN_ID = f"rlm-rlvr-qwen3-4b-depth1-h100-r4-a8-lr1e-4-s150-{RUN_SUFFIX}"
CONFIG_FILENAME = (
    "qwen3_4b_instruct_depth1_r004_a008_lr1e-4_s150_8xh100_"
    f"{RUN_SUFFIX}.toml"
)


def _replace_once(text: str, pattern: str, replacement: str) -> str:
    result, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise RuntimeError(f"Expected exactly one match for {pattern!r}; got {count}.")
    return result


def _replace_all(text: str, old: str, new: str) -> str:
    if old not in text:
        raise RuntimeError(f"Missing expected source text: {old!r}")
    return text.replace(old, new)


def build_config(base: str) -> str:
    text = _replace_once(
        base,
        r"^# Generated by .+$",
        "# Generated by scripts/rlm_rlvr/generate_semantic_delegation_v3_curriculum_config.py.",
    )
    text = _replace_all(text, OLD_RUN_ID, RUN_ID)
    text = _replace_all(
        text,
        "# Data: full balanced BEEG mixture, with Oolong replaced by semantic aggregation v2.",
        "# Data: private full BEEG mixture with Oolong replaced by semantic delegation v3.",
    )
    text = _replace_once(text, r'^output_dir = ".+"$', f'output_dir = "../outputs/{RUN_ID}"')
    text = _replace_all(text, 'dataset_id = "lsteno/BEEG-agents"', f'dataset_id = "{PRIVATE_DATASET_ID}"')
    text = re.sub(r'^data_paths = \[.+\]\n', "", text, flags=re.MULTILINE)
    text = re.sub(r'^eval_data_paths = \[.+\]\n', "", text, flags=re.MULTILINE)
    text = _replace_once(
        text,
        r"^max_trainable_llm_subcalls_per_rollout = 3$",
        "max_trainable_llm_subcalls_per_rollout = 3\nsemantic_child_local_advantage_weight = 0.8",
    )
    text = _replace_once(
        text,
        r"^\[orchestrator\.trace_export\]$",
        """[[orchestrator.buffer.curriculum_phases]]
start_step = 0
end_step = 29
weights = { base = 0.65, semantic_4 = 0.35 }

[[orchestrator.buffer.curriculum_phases]]
start_step = 30
end_step = 79
weights = { base = 0.65, semantic_4 = 0.0875, semantic_8 = 0.2625 }

[[orchestrator.buffer.curriculum_phases]]
start_step = 80
end_step = 149
weights = { base = 0.65, semantic_4 = 0.035, semantic_8 = 0.070, semantic_16 = 0.210, semantic_global = 0.035 }

[orchestrator.trace_export]""",
    )
    text = _replace_once(
        text,
        r"^(\[orchestrator\.buffer\][\s\S]*?seed = 42)$",
        (
            r'\1\ndifficulty_metric = "semantic_progress_metric"'
            r'\nhash_keys = ["example_id"]'
            r'\ncurriculum_bucket_path = "metadata.curriculum_bucket"'
            r'\ncurriculum_base_bucket = "base"'
        ),
    )
    text = _replace_all(text, "max_total_subcalls = 50", "max_total_subcalls = 24")
    text = _replace_all(text, "max_batched_subcalls = 50", "max_batched_subcalls = 16")
    text = _replace_all(
        text,
        "max_batched_subcalls = 16\nsubcall_batch_max_workers = 2",
        'max_batched_subcalls = 16\nsubcall_batch_max_workers = 2\nsubcall_batch_overflow_mode = "reject"',
    )
    text = _replace_all(text, "adaptive_efficiency_gamma = 1.0", "adaptive_efficiency_gamma = 2.0")
    text = _replace_all(
        text,
        'efficiency_penalty_applies_to = "all_rollouts"',
        'efficiency_penalty_applies_to = "correct_only"',
    )
    return text


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    config_path = OUT_DIR / CONFIG_FILENAME
    config_path.write_text(build_config(BASE_CONFIG.read_text()))
    row = {
        "index": 1,
        "run_id": RUN_ID,
        "rank": 4,
        "alpha": 8,
        "lr": "1e-4",
        "max_steps": 150,
        "num_infer_gpus": 4,
        "num_train_gpus": 4,
        "batch_size": 64,
        "rollouts_per_example": 4,
        "max_trainable_llm_subcalls_per_rollout": 3,
        "semantic_child_local_advantage_weight": 0.8,
        "max_total_subcalls": 24,
        "max_batched_subcalls": 16,
        "subcall_batch_overflow_mode": "reject",
        "adaptive_efficiency_beta_max": 1.0,
        "adaptive_efficiency_gamma": 2.0,
        "efficiency_penalty_applies_to": "correct_only",
        "dataset_id": PRIVATE_DATASET_ID,
        "wandb_entity": "lsteno-university-of-twente",
        "wandb_project": "rlm-rlvr",
        "config_path": config_path.relative_to(ROOT).as_posix(),
        "output_dir": f"outputs/{RUN_ID}",
        "status": "pending",
    }
    with (OUT_DIR / "manifest.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(row), lineterminator="\n")
        writer.writeheader()
        writer.writerow(row)
    (OUT_DIR / "manifest.json").write_text(json.dumps([row], indent=2) + "\n")
    print(config_path.relative_to(ROOT))


if __name__ == "__main__":
    main()
