#!/usr/bin/env python3
"""Generate verified dual-contract semantic delegation v4 pilot and full configs."""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
V3_CONFIG_DIR = ROOT / "configs/rlm_rlvr/semantic_delegation_v3_curriculum"
BASE_CONFIG = next(V3_CONFIG_DIR.glob("*.toml"))
OUT_DIR = ROOT / "configs/rlm_rlvr/semantic_delegation_v4_dual_contract"
PRIVATE_DATASET_ID = "lsteno/BEEG-agents-semantic-delegation-v4"
V3_RUN_ID = "rlm-rlvr-qwen3-4b-depth1-h100-r4-a8-lr1e-4-s150-semantic-delegation-v3-curriculum-local80-terminal20-root8-beta1"
RUNS = (
    (30, "pilot"),
    (150, "full"),
)


def run_id(max_steps: int, label: str) -> str:
    return (
        "rlm-rlvr-qwen3-4b-depth1-h100-r4-a8-lr1e-4-"
        f"s{max_steps}-semantic-delegation-v4-dual-verified-branch50-{label}"
    )


def config_filename(max_steps: int, label: str) -> str:
    return (
        "qwen3_4b_instruct_depth1_r004_a008_lr1e-4_"
        f"s{max_steps}_8xh100_semantic-delegation-v4-dual-verified-branch50-{label}.toml"
    )


def _replace_once(text: str, pattern: str, replacement: str) -> str:
    result, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise RuntimeError(f"Expected exactly one match for {pattern!r}; got {count}.")
    return result


def build_config(base: str, *, max_steps: int, label: str) -> str:
    new_run_id = run_id(max_steps, label)
    text = _replace_once(
        base,
        r"^# Generated by .+$",
        "# Generated by scripts/rlm_rlvr/generate_semantic_delegation_v4_configs.py.",
    )
    text = text.replace(V3_RUN_ID, new_run_id)
    text = text.replace("semantic delegation v3", "semantic delegation v4 with verified dual child contracts")
    text = text.replace(
        "# Sweep parameters: rank=4, alpha=8, lr=1e-4, max_steps=150.",
        f"# Sweep parameters: rank=4, alpha=8, lr=1e-4, max_steps={max_steps}.",
    )
    text = _replace_once(text, r"^max_steps = 150$", f"max_steps = {max_steps}")
    text = text.replace(
        'dataset_id = "lsteno/BEEG-agents-semantic-delegation-v3"',
        f'dataset_id = "{PRIVATE_DATASET_ID}"',
    )
    text = _replace_once(
        text,
        r"^(\[trainer\.loss\][\s\S]*?teacher_tau = 0\.0)$",
        r'\1\nnormalization = "branch_sequence"\nsemantic_child_fraction = 0.5',
    )
    text = text.replace(
        "train_plain_llm_subcalls = true\n",
        "train_plain_llm_subcalls = true\nsemantic_record_map_min_records = 8\n",
    )
    return text


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    base = BASE_CONFIG.read_text()
    rows = []
    for index, (max_steps, label) in enumerate(RUNS, start=1):
        filename = config_filename(max_steps, label)
        path = OUT_DIR / filename
        current_run_id = run_id(max_steps, label)
        path.write_text(build_config(base, max_steps=max_steps, label=label))
        rows.append(
            {
                "index": index,
                "run_id": current_run_id,
                "run_type": label,
                "rank": 4,
                "alpha": 8,
                "lr": "1e-4",
                "max_steps": max_steps,
                "num_infer_gpus": 4,
                "num_train_gpus": 4,
                "batch_size": 64,
                "rollouts_per_example": 4,
                "max_trainable_llm_subcalls_per_rollout": 3,
                "semantic_child_local_advantage_weight": 0.8,
                "loss_normalization": "branch_sequence",
                "semantic_child_fraction": 0.5,
                "semantic_record_map_min_records": 8,
                "dataset_id": PRIVATE_DATASET_ID,
                "wandb_entity": "lsteno-university-of-twente",
                "wandb_project": "rlm-rlvr",
                "config_path": path.relative_to(ROOT).as_posix(),
                "output_dir": f"outputs/{current_run_id}",
                "status": "pending" if label == "pilot" else "gated",
            }
        )

    with (OUT_DIR / "manifest.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    (OUT_DIR / "manifest.json").write_text(json.dumps(rows, indent=2) + "\n")
    for row in rows:
        print(row["config_path"])


if __name__ == "__main__":
    main()
