#!/usr/bin/env python3
"""Generate the depth-1 H100 rerun using semantic Oolong aggregation data."""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
BASE_CONFIG = (
    ROOT
    / "configs/rlm_rlvr/rerun_depth1_h100_lora_trainable_subcalls/"
    "qwen3_4b_instruct_sanjaya_depth1_llmonly_r004_a008_lr1e-4_s150_8xh100_"
    "train-subcalls-root8-beta1-ff05-judgeguard-retire-solved-bal35f40v1.toml"
)
OUT_DIR = ROOT / "configs/rlm_rlvr/rerun_depth1_h100_lora_semantic_agg_trainonce"
DATA_DIR_FROM_PRIME_RL = "../data/beeg_agents_balanced_35_40_25_frames40_oolong_semantic_agg_v2"
OLD_RUN_ID = (
    "rlm-rlvr-qwen3-4b-depth1-llmonly-h100-r4-a8-lr1e-4-s150-"
    "train-subcalls-root8-beta1-ff05-judgeguard-retire-solved-bal35f40v1"
)
RUN_SUFFIX = "train-subcalls-root8-beta1-ff05-judgeguard-semanticaggv2-trainonceeasy-bal35f40v1"
RUN_ID = f"rlm-rlvr-qwen3-4b-depth1-llmonly-h100-r4-a8-lr1e-4-s150-{RUN_SUFFIX}"
CONFIG_FILENAME = (
    "qwen3_4b_instruct_sanjaya_depth1_llmonly_r004_a008_lr1e-4_s150_8xh100_"
    f"{RUN_SUFFIX}.toml"
)


def replace_line(text: str, pattern: str, replacement: str) -> str:
    text, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise RuntimeError(f"Expected exactly one replacement for pattern: {pattern}")
    return text


def replace_all(text: str, old: str, new: str) -> str:
    if old not in text:
        raise RuntimeError(f"Missing text to replace: {old}")
    return text.replace(old, new)


def build_config(base: str) -> str:
    text = replace_line(
        base,
        r"^# Generated by .+$",
        "# Generated by scripts/rlm_rlvr/generate_depth1_h100_semantic_agg_trainonce_rerun_config.py.",
    )
    text = replace_all(text, OLD_RUN_ID, RUN_ID)
    text = replace_line(text, r'^output_dir = ".+"$', f'output_dir = "../outputs/{RUN_ID}"')
    text = replace_all(
        text,
        "../data/beeg_agents_balanced_35_40_25_frames40_v1",
        DATA_DIR_FROM_PRIME_RL,
    )
    text = replace_line(text, r"^online_filter_easy = true$", "online_filter_easy = false")
    text = replace_all(
        text,
        "# Stable LoRA/depth-2 setup: 4 inference / 4 train with filesystem checkpoint broadcast enabled.\n",
        "# Stable LoRA/depth-2 setup: 4 inference / 4 train with filesystem checkpoint broadcast enabled.\n"
        "# Data: full balanced BEEG mixture, with Oolong replaced by semantic aggregation v2.\n",
    )
    return text


def main() -> None:
    base = BASE_CONFIG.read_text()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    config_path = OUT_DIR / CONFIG_FILENAME
    config_path.write_text(build_config(base))

    row = {
        "index": 1,
        "run_id": RUN_ID,
        "rank": 4,
        "alpha": 8,
        "lr": "1e-4",
        "max_steps": 150,
        "max_async_level": 2,
        "max_off_policy_steps": 4,
        "hard_cooldown_steps": 5,
        "seed": 42,
        "batch_size": 64,
        "rollouts_per_example": 4,
        "num_infer_gpus": 4,
        "num_train_gpus": 4,
        "inference_dp": 4,
        "train_worker_count": 32,
        "eval_worker_count": 16,
        "rollout_timeout_seconds": 400,
        "repl_timeout_seconds": 300,
        "max_total_subcalls": 50,
        "max_batched_subcalls": 50,
        "max_trainable_llm_subcalls_per_rollout": 3,
        "adaptive_efficiency_beta_max": 1.0,
        "adaptive_efficiency_gamma": 1.0,
        "adaptive_efficiency_solve_rate_floor": 0.25,
        "adaptive_efficiency_cost_basis": "weighted_turn_tokens",
        "efficiency_root_token_multiplier": 8.0,
        "efficiency_plain_subcall_token_multiplier": 1.0,
        "max_turn_penalty": 0.5,
        "judge_candidate_max_chars": 8192,
        "judge_question_max_chars": 32768,
        "judge_expected_max_chars": 8192,
        "subcall_batch_max_workers": 2,
        "online_filter_easy": "false",
        "easy_threshold": 1.0,
        "easy_fraction": 0.0,
        "experiment_depth": 1,
        "runtime_max_depth": 0,
        "prompt_variant": "sanjaya_text_depth1_llm_only_v1",
        "config_path": config_path.relative_to(ROOT).as_posix(),
        "output_dir": f"outputs/{RUN_ID}",
        "train_data_path": f"{DATA_DIR_FROM_PRIME_RL}/train.parquet",
        "eval_data_path": f"{DATA_DIR_FROM_PRIME_RL}/eval.parquet",
        "wandb_entity": "lsteno-university-of-twente",
        "wandb_project": "rlm-rlvr",
        "wandb_name": RUN_ID,
        "base_config": BASE_CONFIG.relative_to(ROOT).as_posix(),
        "status": "pending",
        "notes": (
            "full_balanced_dataset_with_oolong_semantic_agg_v2=true;"
            "train_plain_llm_subcalls=true;max_trainable_llm_subcalls_per_rollout=3;"
            "adaptive_efficiency_cost_basis=weighted_turn_tokens;root_token_multiplier=8.0;"
            "adaptive_efficiency_beta_max=1.0;max_turn_penalty=0.5;"
            "judge_guard_chars=8192/32768/8192;online_filter_easy=false;"
            "easy_threshold=1.0;easy_fraction=0.0"
        ),
    }
    fieldnames = list(row.keys())
    with (OUT_DIR / "manifest.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerow(row)
    (OUT_DIR / "manifest.json").write_text(json.dumps([row], indent=2) + "\n")
    print(f"Wrote rerun config and manifests under {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
