#!/usr/bin/env python3
"""Generate the packet-credit semantic delegation v6 pilot config."""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
BASE_CONFIG = next(
    (ROOT / "configs/rlm_rlvr/semantic_delegation_v5_natural_credit").glob(
        "*s30*pilot.toml"
    )
)
OUT_DIR = ROOT / "configs/rlm_rlvr/semantic_delegation_v6_packet_credit"
DATASET_ID = "lsteno/BEEG-agents-semantic-delegation-v6"
OLD_RUN_ID = "rlm-rlvr-qwen3-4b-depth1-h100-r4-a8-lr1e-4-s30-semantic-delegation-v5-natural-credit-rootrollout-betamin01-pilot"
RUN_ID = "rlm-rlvr-qwen3-4b-depth1-h100-r4-a8-lr1e-4-s50-semantic-delegation-v6-packet-credit-tiebreak005-root60-pilot"
FILENAME = (
    "qwen3_4b_instruct_depth1_r004_a008_lr1e-4_s50_8xh100_"
    "semantic-delegation-v6-packet-credit-tiebreak005-root60-pilot.toml"
)


def _replace_once(text: str, pattern: str, replacement: str) -> str:
    result, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise RuntimeError(f"Expected exactly one match for {pattern!r}; got {count}.")
    return result


def build_config(base: str) -> str:
    text = _replace_once(
        base,
        r"^# Generated by .+$",
        "# Generated by scripts/rlm_rlvr/generate_semantic_delegation_v6_configs.py.",
    )
    text = text.replace(OLD_RUN_ID, RUN_ID)
    text = text.replace(
        "semantic delegation v5 with natural verifier-invisible child credit",
        "semantic delegation v6 with natural complete-packet child credit",
    )
    text = text.replace(
        "# Sweep parameters: rank=4, alpha=8, lr=1e-4, max_steps=30.",
        "# Pilot parameters: rank=4, alpha=8, lr=1e-4, max_steps=50, eight rollouts per prompt.",
    )
    text = _replace_once(text, r"^max_steps = 30$", "max_steps = 50")
    text = _replace_once(text, r"^interval = 25$", "interval = 10")
    text = _replace_once(text, r"^keep_last = 2$", "keep_last = 6")
    text = _replace_once(
        text, r"^rollouts_per_example = 4$", "rollouts_per_example = 8"
    )
    text = _replace_once(
        text, r"^semantic_child_fraction = 0\.5$", "semantic_child_fraction = 0.4"
    )
    text = text.replace(
        'dataset_id = "lsteno/BEEG-agents-semantic-delegation-v5"',
        f'dataset_id = "{DATASET_ID}"',
    )
    text = _replace_once(
        text,
        r'^difficulty_metric = "semantic_progress_metric"$',
        'difficulty_metric = "semantic_chunk_accuracy_metric"',
    )
    curriculum = """[[orchestrator.buffer.curriculum_phases]]
start_step = 0
end_step = 19
weights = { base = 0.65, sentiment_small = 0.35 }

[[orchestrator.buffer.curriculum_phases]]
start_step = 20
end_step = 34
weights = { base = 0.65, sentiment_small = 0.10, sentiment_medium = 0.15, advanced_small = 0.10 }

[[orchestrator.buffer.curriculum_phases]]
start_step = 35
end_step = 49
weights = { base = 0.65, sentiment_medium = 0.15, advanced_small = 0.10, advanced_medium = 0.10 }

"""
    text, count = re.subn(
        r"\[\[orchestrator\.buffer\.curriculum_phases\]\].*?(?=\[orchestrator\.trace_export\])",
        curriculum,
        text,
        count=1,
        flags=re.DOTALL,
    )
    if count != 1:
        raise RuntimeError("Could not replace curriculum phase block.")
    text = text.replace("subcall_max_tokens = 2048", "subcall_max_tokens = 512")
    text = text.replace("max_batched_subcalls = 16", "max_batched_subcalls = 20")
    adaptive_block = """efficiency_penalty_mode = "adaptive_group"
adaptive_efficiency_beta_min = 0.10
adaptive_efficiency_beta_max = 1.0
adaptive_efficiency_gamma = 2.0
adaptive_efficiency_solve_rate_floor = 0.25
adaptive_efficiency_cost_basis = "weighted_turn_tokens"
efficiency_root_token_multiplier = 8.0
efficiency_plain_subcall_token_multiplier = 1.0
efficiency_penalty_applies_to = "all_rollouts"
"""  # noqa: E501
    tie_break_block = """efficiency_penalty_mode = "accuracy_stratified_group"
adaptive_efficiency_cost_basis = "weighted_turn_tokens"
efficiency_root_token_multiplier = 8.0
efficiency_plain_subcall_token_multiplier = 1.0
efficiency_penalty_applies_to = "all_rollouts"
efficiency_tie_break_max = 0.05
"""
    if text.count(adaptive_block) != 1:
        raise RuntimeError("Expected one adaptive training reward block.")
    text = text.replace(adaptive_block, tie_break_block)
    text = _replace_once(text, r"^interval = 25$", "interval = 10")
    text = _replace_once(text, r"^eval_base_model = false$", "eval_base_model = true")

    eval_start = text.index("[[orchestrator.eval.env]]")
    eval_end = text.index("[inference]", eval_start)
    eval_block = text[eval_start:eval_end]
    semantic_eval = eval_block.replace(
        'name = "rlm_rlvr_eval"', 'name = "semantic_eval"'
    )
    semantic_eval = semantic_eval.replace("worker_count = 16", "worker_count = 8")
    semantic_eval = semantic_eval.replace(
        'dataset_eval_split = "eval"', 'dataset_eval_split = "semantic_eval"'
    )
    semantic_eval = semantic_eval.replace(
        "/live_traces_eval", "/live_traces_semantic_eval"
    )
    mixed_eval = eval_block.replace('name = "rlm_rlvr_eval"', 'name = "mixed_eval"')
    mixed_eval = mixed_eval.replace("worker_count = 16", "worker_count = 8")
    mixed_eval = mixed_eval.replace("num_examples = 64", "num_examples = 32")
    mixed_eval = mixed_eval.replace("max_eval_examples = 256", "max_eval_examples = 32")
    mixed_eval = mixed_eval.replace("/live_traces_eval", "/live_traces_mixed_eval")
    text = text[:eval_start] + semantic_eval + mixed_eval + text[eval_end:]
    return text


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / FILENAME
    path.write_text(build_config(BASE_CONFIG.read_text()))
    row = {
        "index": 1,
        "run_id": RUN_ID,
        "run_type": "pilot",
        "rank": 4,
        "alpha": 8,
        "lr": "1e-4",
        "max_steps": 50,
        "num_infer_gpus": 4,
        "num_train_gpus": 4,
        "batch_size": 64,
        "rollouts_per_example": 8,
        "max_trainable_llm_subcalls_per_rollout": 3,
        "semantic_child_local_advantage_weight": 0.8,
        "semantic_child_fraction": 0.4,
        "efficiency_penalty_mode": "accuracy_stratified_group",
        "efficiency_tie_break_max": 0.05,
        "dataset_id": DATASET_ID,
        "wandb_entity": "lsteno-university-of-twente",
        "wandb_project": "rlm-rlvr",
        "config_path": path.relative_to(ROOT).as_posix(),
        "output_dir": f"outputs/{RUN_ID}",
        "status": "pending",
    }
    with (OUT_DIR / "manifest.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(row), lineterminator="\n")
        writer.writeheader()
        writer.writerow(row)
    (OUT_DIR / "manifest.json").write_text(json.dumps([row], indent=2) + "\n")
    print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
